[package]
name = "wbem-client"
version = "0.1.0"
license = "MIT"
authors = ["IML Team <iml@whamcloud.com>"]
description = "An asynchronous Web-Based Enterprise Management (WBEM) client"
repository = "https://github.com/whamcloud/integrated-manager-for-lustre/tree/master/wbem-client"
edition = "2018"

[dependencies]
async-trait = "0.1"
base64 = "0.12"
bytes = "0.5"
futures = "0.3"
quick-xml = { version = "0.18", features = ["serialize"] }
reqwest = { version = "0.10", default-features = false, features = ["rustls-tls"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"


[dev-dependencies]
insta = "0.16"