[package]
name = "iml-api-utils"
description = "Utilities for working with the IML API"
version = "0.3.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
license = "MIT"

[dependencies]
lazy_static = "1.4.0"

[dependencies.regex]
version = "1.3"
default-features = false
features = ["std", "unicode-perl"]

[dev-dependencies]
rand_core = "0.5.1"
rand_xoshiro = "0.4.0"
